import { relations } from "drizzle-orm";
import { pgTable, text, uuid, jsonb, boolean, integer } from "drizzle-orm/pg-core";
import { user } from "./auth";

// User settings including AI provider configuration
export const userSettings = pgTable("user_settings", {
	id: uuid("id").defaultRandom().primaryKey(),
	userId: text("user_id")
		.notNull()
		.unique()
		.references(() => user.id, { onDelete: "cascade" }),

	// AI Provider settings (encrypted in production)
	aiProvider: text("ai_provider").default("openai"), // openai, anthropic, google
	aiApiKey: text("ai_api_key"), // Encrypted user's API key
	aiModel: text("ai_model"), // gpt-4o, claude-sonnet-4-20250514, gemini-1.5-pro, etc.

	// UI preferences
	theme: text("theme").default("system"), // light, dark, system
	defaultLanguage: text("default_language").default("en"),

	// Feature flags
	preferences: jsonb("preferences").$type<{
		autoGenerateDefinitions: boolean;
		showPronunciation: boolean;
		showHindiTranslation: boolean;
		defaultView: "grid" | "list";
	}>(),

	// Onboarding state
	isOnboarded: boolean("is_onboarded").default(false).notNull(),
	onboardingStep: integer("onboarding_step").default(0).notNull(), // 0-5 step index
});

// Relations
export const userSettingsRelations = relations(userSettings, ({ one }) => ({
	user: one(user, {
		fields: [userSettings.userId],
		references: [user.id],
	}),
}));
